name: pembekalan_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #plugin untuk save data sederhana (key-value)
  shared_preferences: ^2.3.5

  #untuk date time formatter
  #https://pub.dev/packages/intl
  intl: ^0.20.1

  #untuk http connection
  #https://pub.dev/packages/http
  http: ^1.2.2

  #untuk loading
  #https://pub.dev/packages/progress_dialog_null_safe
  progress_dialog_null_safe: ^3.0.0
  simple_fontellico_progress_dialog: ^0.3.0

  #membuat carousel image
  #https://pub.dev/packages/carousel_slider
  carousel_slider: ^5.0.0

  #library pinch zoom image
  #https://pub.dev/packages/pinch_zoom
  pinch_zoom: ^2.0.0
  #zoom_pinch_overlay 1.4.3 #next cobain

  #handle image dari camera & gallery
  #https://pub.dev/packages/image_picker
  image_picker: ^1.1.2

  #handle database sqlite
  #https://pub.dev/packages/sqflite
  sqflite: ^2.4.1

  #untuk handle file external & path explorer
  #https://pub.dev/packages/path
  path: ^1.9.0

  #untuk handle lokasi
  #https://pub.dev/packages/geolocator
  geolocator: ^13.0.2

  #untuk handle map dng googlemaps
  #https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #untuk mendaftarkan berbagai asset image yang akan digunakan
  assets:
  - assets/images/logo_xa.png

  #untuk mendaftarkan custom font yang akan digunakan
  fonts:
    - family: BiomeRegular
      fonts:
        - asset: assets/fonts/biome_regular.ttf
